# Generated by Django 2.2.7 on 2019-11-16 03:45

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import web.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GoodreadsAuthor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=web.utils.now, editable=False)),
                ('updated_at', models.DateTimeField(default=web.utils.now, editable=False)),
                ('goodreads_id', models.IntegerField()),
                ('url', models.TextField()),
                ('first_name', models.TextField()),
                ('last_name', models.TextField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GoodreadsBook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=web.utils.now, editable=False)),
                ('updated_at', models.DateTimeField(default=web.utils.now, editable=False)),
                ('goodreads_id', models.IntegerField()),
                ('url', models.TextField()),
                ('title', models.TextField()),
                ('authors', models.ManyToManyField(related_name='books', to='web.GoodreadsAuthor')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GoodreadsSeries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=web.utils.now, editable=False)),
                ('updated_at', models.DateTimeField(default=web.utils.now, editable=False)),
                ('goodreads_id', models.IntegerField()),
                ('url', models.TextField()),
                ('title', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GoodreadsUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=web.utils.now, editable=False)),
                ('updated_at', models.DateTimeField(default=web.utils.now, editable=False)),
                ('goodreads_id', models.IntegerField()),
                ('url', models.TextField()),
                ('first_name', models.TextField()),
                ('last_name', models.TextField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='NotionDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=web.utils.now, editable=False)),
                ('updated_at', models.DateTimeField(default=web.utils.now, editable=False)),
                ('notion_id', models.TextField()),
                ('title', models.TextField()),
                ('url', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Text',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=web.utils.now, editable=False)),
                ('updated_at', models.DateTimeField(default=web.utils.now, editable=False)),
                ('text', models.TextField()),
                ('embedding', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('projection', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('source_author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='web.GoodreadsAuthor')),
                ('source_book', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='web.GoodreadsBook')),
                ('source_notion_document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='web.NotionDocument')),
                ('source_series', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='web.GoodreadsSeries')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GoodreadsShelf',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=web.utils.now, editable=False)),
                ('updated_at', models.DateTimeField(default=web.utils.now, editable=False)),
                ('goodreads_id', models.IntegerField()),
                ('url', models.TextField()),
                ('books', models.ManyToManyField(to='web.GoodreadsBook')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='goodreadsbook',
            name='series',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='books', to='web.GoodreadsSeries'),
        ),
    ]
