# Generated by Django 2.2.7 on 2019-11-21 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='text',
            unique_together={('text', 'source_book', 'source_notion_document')},
        ),
    ]
