# Generated by Django 2.2.7 on 2019-11-27 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_auto_20191121_0924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notiondocument',
            name='notion_id',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='notiondocument',
            name='title',
            field=models.TextField(blank=True, null=True),
        ),
    ]
