# Generated by Django 2.2.7 on 2019-11-28 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_auto_20191127_2308'),
    ]

    operations = [
        migrations.AddField(
            model_name='notiondocument',
            name='is_scraping_root',
            field=models.BooleanField(default=False),
        ),
    ]
