# Generated by Django 2.2.7 on 2019-12-12 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_auto_20191212_0831'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='document',
            unique_together={('source', 'embedding_type')},
        ),
    ]
