# Generated by Django 2.2.7 on 2019-11-28 00:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_notiondocument_is_scraping_root'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notiondocument',
            old_name='is_scraping_root',
            new_name='bookmarked',
        ),
    ]
