# Generated by Django 2.2.7 on 2019-12-13 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_auto_20191212_0833'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='embedding_type',
            field=models.IntegerField(blank=True, choices=[(0, 'TF_IDF'), (1, 'BERT'), (2, 'LEMMATIZED_TF_IDF')], null=True),
        ),
    ]
