# Generated by Django 2.2.7 on 2019-11-28 00:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_auto_20191128_0048'),
    ]

    operations = [
        migrations.AddField(
            model_name='notiondocument',
            name='parent_notion_document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parent_document', to='web.NotionDocument'),
        ),
    ]
