# Generated by Django 2.2.7 on 2019-11-28 03:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_auto_20191128_0115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notiondocument',
            name='parent_notion_document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parent_document', to='web.NotionDocument'),
        ),
    ]
