# Generated by Django 2.2.7 on 2019-11-28 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0008_auto_20191128_0302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notiondocument',
            name='notion_id',
            field=models.TextField(blank=True, null=True, unique=True),
        ),
    ]
