# Generated by Django 2.2.7 on 2019-11-30 20:47

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0009_auto_20191128_0508'),
    ]

    operations = [
        migrations.AddField(
            model_name='notiondocument',
            name='embedding',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
