# Generated by Django 2.2.7 on 2019-12-03 02:45

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import web.utils


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0010_notiondocument_embedding'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotionDatabase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=web.utils.now, editable=False)),
                ('updated_at', models.DateTimeField(default=web.utils.now, editable=False)),
                ('url', models.TextField()),
                ('notion_id', models.TextField(blank=True, null=True, unique=True)),
                ('title', models.TextField(blank=True, null=True)),
                ('schema', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('anki_front_html_template', models.TextField(blank=True, null=True)),
                ('anki_back_html_template', models.TextField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='notiondocument',
            name='bookmarked',
        ),
        migrations.RemoveField(
            model_name='notiondocument',
            name='parent_notion_document',
        ),
        migrations.AddField(
            model_name='notiondocument',
            name='parent_database',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='web.NotionDatabase'),
            preserve_default=False,
        ),
    ]
