# Generated by Django 2.2.7 on 2019-12-11 04:30

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0011_auto_20191203_0245'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notiondocument',
            old_name='embedding',
            new_name='bert_embedding',
        ),
        migrations.AddField(
            model_name='notiondocument',
            name='tfidf_embedding',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='notiondatabase',
            name='anki_back_html_template',
            field=models.TextField(blank=True, help_text='Same syntax as above.', null=True),
        ),
        migrations.AlterField(
            model_name='notiondatabase',
            name='anki_front_html_template',
            field=models.TextField(blank=True, help_text='    <strong>Prerequisite</strong>: "Schema" field must be populated.<br><br>\n    These templates are used to create an Anki card for each record in this database. The syntax is HTML plus Notion database properties as "slugs" (the property name, but lower cased and snake cased). Slugs should also be surrounded by double curly braces.<br>\n    See Schema JSON above for valid slugs (you\'ll need to scrape this DB first).<br>\n    Several special properties are also valid slugs: <code>{{text}}</code> (the full contents of the note), <code>{{url}}</code> (the Notion URL of the note), <code>{{title}}</code>, and <code>{{link}}</code> (a shortcut for <code>&lt;a href="{{url}}&gt;{{title}}&lt;/a&gt;</code>").<br><br>\n    Example: <code>&lt;div&gt;{{link}}&lt;br&gt;{{created_at}}&lt;/div&gt;</code>\n    ', null=True),
        ),
        migrations.AlterField(
            model_name='notiondatabase',
            name='schema',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, help_text="<strong>Do not fill.</strong> This field is automatically populated by the 'scrape self' action on the Databases overview page.", null=True),
        ),
        migrations.AlterField(
            model_name='notiondatabase',
            name='url',
            field=models.TextField(help_text='<strong>Required.</strong>'),
        ),
    ]
